//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartsdd) DeepCopyInto(out *AzureVMSchedulerStartsdd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartsdd.
func (in *AzureVMSchedulerStartsdd) DeepCopy() *AzureVMSchedulerStartsdd {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartsdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStartsdd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartsddList) DeepCopyInto(out *AzureVMSchedulerStartsddList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVMSchedulerStartsdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartsddList.
func (in *AzureVMSchedulerStartsddList) DeepCopy() *AzureVMSchedulerStartsddList {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartsddList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStartsddList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartsddSpec) DeepCopyInto(out *AzureVMSchedulerStartsddSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartsddSpec.
func (in *AzureVMSchedulerStartsddSpec) DeepCopy() *AzureVMSchedulerStartsddSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartsddSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStartsddStatus) DeepCopyInto(out *AzureVMSchedulerStartsddStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStartsddStatus.
func (in *AzureVMSchedulerStartsddStatus) DeepCopy() *AzureVMSchedulerStartsddStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStartsddStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopsdd) DeepCopyInto(out *AzureVMSchedulerStopsdd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopsdd.
func (in *AzureVMSchedulerStopsdd) DeepCopy() *AzureVMSchedulerStopsdd {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopsdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStopsdd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopsddList) DeepCopyInto(out *AzureVMSchedulerStopsddList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVMSchedulerStopsdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopsddList.
func (in *AzureVMSchedulerStopsddList) DeepCopy() *AzureVMSchedulerStopsddList {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopsddList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVMSchedulerStopsddList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopsddSpec) DeepCopyInto(out *AzureVMSchedulerStopsddSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopsddSpec.
func (in *AzureVMSchedulerStopsddSpec) DeepCopy() *AzureVMSchedulerStopsddSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopsddSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVMSchedulerStopsddStatus) DeepCopyInto(out *AzureVMSchedulerStopsddStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVMSchedulerStopsddStatus.
func (in *AzureVMSchedulerStopsddStatus) DeepCopy() *AzureVMSchedulerStopsddStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVMSchedulerStopsddStatus)
	in.DeepCopyInto(out)
	return out
}
