# permissions for end users to view awsvmschedulerstartsdds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsvmschedulerstartsdd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator-sdd
    app.kubernetes.io/part-of: vm-scheduler-operator-sdd
    app.kubernetes.io/managed-by: kustomize
  name: awsvmschedulerstartsdd-viewer-role
rules:
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsdds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsdds/status
  verbs:
  - get
