//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsdd) DeepCopyInto(out *AWSVMSchedulerStartsdd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsdd.
func (in *AWSVMSchedulerStartsdd) DeepCopy() *AWSVMSchedulerStartsdd {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStartsdd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsddList) DeepCopyInto(out *AWSVMSchedulerStartsddList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSVMSchedulerStartsdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsddList.
func (in *AWSVMSchedulerStartsddList) DeepCopy() *AWSVMSchedulerStartsddList {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsddList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStartsddList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsddSpec) DeepCopyInto(out *AWSVMSchedulerStartsddSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsddSpec.
func (in *AWSVMSchedulerStartsddSpec) DeepCopy() *AWSVMSchedulerStartsddSpec {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsddSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsddStatus) DeepCopyInto(out *AWSVMSchedulerStartsddStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsddStatus.
func (in *AWSVMSchedulerStartsddStatus) DeepCopy() *AWSVMSchedulerStartsddStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsddStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsdd) DeepCopyInto(out *AWSVMSchedulerStopsdd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsdd.
func (in *AWSVMSchedulerStopsdd) DeepCopy() *AWSVMSchedulerStopsdd {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStopsdd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsddList) DeepCopyInto(out *AWSVMSchedulerStopsddList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSVMSchedulerStopsdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsddList.
func (in *AWSVMSchedulerStopsddList) DeepCopy() *AWSVMSchedulerStopsddList {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsddList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStopsddList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsddSpec) DeepCopyInto(out *AWSVMSchedulerStopsddSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsddSpec.
func (in *AWSVMSchedulerStopsddSpec) DeepCopy() *AWSVMSchedulerStopsddSpec {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsddSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsddStatus) DeepCopyInto(out *AWSVMSchedulerStopsddStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsddStatus.
func (in *AWSVMSchedulerStopsddStatus) DeepCopy() *AWSVMSchedulerStopsddStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsddStatus)
	in.DeepCopyInto(out)
	return out
}
