//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsdd) DeepCopyInto(out *GCPVMSchedulerStartsdd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsdd.
func (in *GCPVMSchedulerStartsdd) DeepCopy() *GCPVMSchedulerStartsdd {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartsdd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsddList) DeepCopyInto(out *GCPVMSchedulerStartsddList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStartsdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsddList.
func (in *GCPVMSchedulerStartsddList) DeepCopy() *GCPVMSchedulerStartsddList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsddList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartsddList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsddSpec) DeepCopyInto(out *GCPVMSchedulerStartsddSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsddSpec.
func (in *GCPVMSchedulerStartsddSpec) DeepCopy() *GCPVMSchedulerStartsddSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsddSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsddStatus) DeepCopyInto(out *GCPVMSchedulerStartsddStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsddStatus.
func (in *GCPVMSchedulerStartsddStatus) DeepCopy() *GCPVMSchedulerStartsddStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsddStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsdd) DeepCopyInto(out *GCPVMSchedulerStopsdd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsdd.
func (in *GCPVMSchedulerStopsdd) DeepCopy() *GCPVMSchedulerStopsdd {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopsdd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsddList) DeepCopyInto(out *GCPVMSchedulerStopsddList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStopsdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsddList.
func (in *GCPVMSchedulerStopsddList) DeepCopy() *GCPVMSchedulerStopsddList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsddList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopsddList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsddSpec) DeepCopyInto(out *GCPVMSchedulerStopsddSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsddSpec.
func (in *GCPVMSchedulerStopsddSpec) DeepCopy() *GCPVMSchedulerStopsddSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsddSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsddStatus) DeepCopyInto(out *GCPVMSchedulerStopsddStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsddStatus.
func (in *GCPVMSchedulerStopsddStatus) DeepCopy() *GCPVMSchedulerStopsddStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsddStatus)
	in.DeepCopyInto(out)
	return out
}
